/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    fontFamily: {
      inter: ['Inter', 'sans-serif'],
      sans: ['Inter', 'sans-serif'],
    },
    extend: {
      colors: {
        // Horizon UI Color Palette
        primary: '#1978e5',
        'primary-container': '#1461cc',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#93c5fd',
        'primary-fixed': '#bfdbfe',
        'primary-fixed-dim': '#93c5fd',
        'on-primary-fixed': '#1e3a8a',
        'on-primary-fixed-variant': '#1e3a8a',

        secondary: '#475569',
        'secondary-container': '#e2e8f0',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#0f172a',
        'secondary-fixed': '#cbd5e1',
        'secondary-fixed-dim': '#94a3b8',
        'on-secondary-fixed': '#1e293b',
        'on-secondary-fixed-variant': '#334155',

        tertiary: '#64748b',
        'tertiary-container': '#f1f5f9',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#0f172a',
        'tertiary-fixed': '#e2e8f0',
        'tertiary-fixed-dim': '#cbd5e1',
        'on-tertiary-fixed': '#0f172a',
        'on-tertiary-fixed-variant': '#334155',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        background: '#f8fafc',
        'on-background': '#0f172a',
        surface: '#ffffff',
        'surface-dim': '#e2e8f0',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8fafc',
        'surface-container': '#f8fafc',
        'surface-container-high': '#e2e8f0',
        'surface-container-highest': '#cbd5e1',
        'on-surface': '#0f172a',
        'on-surface-variant': '#475569',
        'inverse-surface': '#1e293b',
        'inverse-on-surface': '#f1f5f9',
        outline: '#94a3b8',
        'outline-variant': '#cbd5e1',
        'surface-tint': '#1978e5',
        'surface-variant': '#f1f5f9',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.75rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.125rem',
        full: '9999px',
      },
      spacing: {
        'unit': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'gutter': '16px',
        'container-padding': '24px',
      },
      fontSize: {
        'caption-sm': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.43', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.43', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '1.33', fontWeight: '600' }],
        'price-lg': ['20px', { lineHeight: '1.0', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.25', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '1.33', fontWeight: '700' }],
        'display-xl': ['34px', { lineHeight: '1.24', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
